export function createLibraryUI({state,api,openDialog,dialog,escape,toast}){
  let query='',source='all',bookmarked=false,cursor='',previous=[],timer=null,loading=false,reader=null;
  const data=()=>state.traceLibrary??{items:[],summary:{saved:0,added_week:0,recording:0,bookmarked:0},attempts:[]};
  const when=v=>v?new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not available';
  const status=item=>item.state==='RECORDING'?'Recording':item.state==='INTERRUPTED'?'Interrupted':item.state==='IMPORTED'?'Uploaded history':'Saved';
  const display=item=>({PENDING:'Preparing readable view',PARTIAL:'Some content needs a display update',UNREADABLE:'Original saved; readable view needs an update',ERROR:'Original saved; readable view needs an update'}[item.projection]??'');
  function queryString(){const p=new URLSearchParams({limit:'30'});if(query)p.set('q',query);if(source!=='all')p.set('source',source);if(bookmarked)p.set('bookmarked','true');if(cursor)p.set('cursor',cursor);return '?'+p;}
  function row(item){return `<article class="library-row" data-testid="conversation-row" data-trace-id="${escape(item.trace_id)}"><div class="library-origin">${escape(item.source)}<small>${item.origin==='upload'?'Uploaded history':'Captured through thot market'}</small></div><div class="library-description"><button class="library-title" data-action="library-open" data-id="${escape(item.trace_id)}">${escape(item.title)}</button><p>${escape(item.project||'Saved conversation')} · ${item.session_at?escape(when(item.session_at)):'Session date unavailable'}</p>${display(item)?`<p class="library-display-note">${escape(display(item))}</p>`:''}${item.note||item.answer_preview?`<p class="library-note-preview">${escape((item.note||item.answer_preview).slice(0,220))}</p>`:''}</div><div class="library-progress"><span class="pill ${item.state==='RECORDING'?'success':'neutral'}">${status(item)}</span><small>${item.last_checkpoint_at?`Saved through ${escape(when(item.last_checkpoint_at))}`:`Added ${escape(when(item.created_at))}`}</small><small>${item.segments>1?`${item.segments} captures of this conversation`:`${item.turn_count} readable turns`}${item.native_conversations>1?` · ${item.native_conversations} native conversations in this recording`:''}${item.bookmarked?' · Bookmarked':''}</small></div><button class="text-button" data-action="library-bookmark" data-id="${escape(item.trace_id)}" data-value="${!item.bookmarked}" aria-label="${item.bookmarked?'Remove bookmark':'Bookmark'} ${escape(item.title)}">${item.bookmarked?'★':'☆'}</button></article>`;}
  function body(){
    const d=data(),s=d.summary;
    return `<div class="section-head"><div><p class="eyebrow">Private by default</p><h1>Your traces</h1><p>Your Codex and Claude Code conversations, private until you choose to list them. Upload one coding-session .jsonl file, up to 2 MB, or capture a new session.</p></div><div class="library-actions"><button class="button" data-action="start-agent-capture">Capture a conversation</button><button class="button secondary" data-action="import-research" title="One Claude Code or Codex coding-session .jsonl file, up to 2 MB">Upload session file</button></div></div>
      <section class="library-metrics" aria-label="Collection progress"><article><small>Saved records</small><strong>${s.saved}</strong><p>${s.added_week?`+${s.added_week} added this week`:'Your first saved conversation will appear here.'}</p></article><article><small>Recording now</small><strong>${s.recording}</strong><p>Checkpoints arrive while you work.</p></article><article><small>Bookmarked for reuse</small><strong>${s.bookmarked}</strong><p>${s.bookmarked?'Useful work you chose to keep close.':'Mark an answer or session worth returning to.'}</p></article></section>
      <form id="library-search" class="library-toolbar"><label><span class="sr-only">Search titles, projects, notes and source</span><input id="library-query" name="q" type="search" value="${escape(query)}" placeholder="Find a title, project or note"></label><label><span class="sr-only">Coding tool</span><select id="library-source" name="source"><option value="all">All tools</option><option value="codex" ${source==='codex'?'selected':''}>Codex</option><option value="claude" ${source==='claude'?'selected':''}>Claude Code</option></select></label><button class="button secondary small" type="submit">Search</button><button type="button" class="text-button" data-action="library-filter-bookmarks" aria-pressed="${bookmarked}">${bookmarked?'★ Bookmarked':'☆ Bookmarks'}</button><button type="button" class="text-button" data-action="library-connections">Connected tools</button></form>
      ${d.attempts?.some(a=>a.parts||a.error_code)?`<div class="library-attention">${d.attempts.filter(a=>a.parts||a.error_code).map(a=>`<p>${escape(a.client==='claude'?'Claude Code':'Codex')}: ${a.parts} exchanges received, awaiting a verified checkpoint.${a.error_code?` Save needs attention (${escape(a.error_code)}). Your helper retains recovery details.`:''}</p>`).join('')}</div>`:''}
      <div class="library-list">${d.items.length?d.items.map(row).join(''):`<div class="empty"><h3>${query||source!=='all'||bookmarked?'No conversations match yet.':'Start with a conversation worth keeping.'}</h3><p>${s.saved?'Try another search or clear your filters.':'Capture with your usual Codex or Claude Code login, or upload a coding-session .jsonl file. Then read, bookmark and annotate your work here.'}</p></div>`}</div>
      <div class="library-footer"><span>${d.total_matches??s.saved} ${query||bookmarked||source!=='all'?'matching ':''}records · updated ${escape(when(d.refreshed_at))}</span><div>${previous.length?'<button class="text-button" data-action="library-previous">← Previous</button>':''}${d.next_cursor?'<button class="text-button" data-action="library-next">Next →</button>':''}</div></div>
      <div class="library-value"><div><h3>Your work is accumulating.</h3><p>${s.saved?`${s.saved} records kept privately${s.bookmarked?`, with ${s.bookmarked} bookmarked for reuse`:''}. Open one to revisit its answers or add a note about why it matters.`:'Saving a conversation creates a persistent record you can revisit, organize and choose to share later.'}</p></div><div><h3>Offers are separate.</h3><p>${state.candidates?.filter(c=>c.status==='USER_AUTH_PENDING').length?`${state.candidates.filter(c=>c.status==='USER_AUTH_PENDING').length} simulated offers await your review in Offers.`:'Saving a trace does not create an offer or payment. Any demonstration assay is an estimate, not a market price. Offers and receipts stay separate.'}</p><button class="text-button" data-view="market">View offers →</button></div></div>`;
  }
  function sectionHTML(){return `<section id="conversation-library">${body()}</section>`;}
  function paint(){const el=document.querySelector('#conversation-library');if(el&&state.role==='user'&&state.view==='vault')el.innerHTML=body();}
  async function load(){if(loading||!state.loaded||state.role!=='user')return;loading=true;try{const result=await api('/v1/contributor/library'+queryString());state.traceLibrary=result;paint();}finally{loading=false;}}
  function ready(){clearTimeout(timer);timer=setTimeout(async()=>{try{if(state.loaded&&state.role==='user'&&state.view==='vault'&&!document.hidden&&!document.activeElement?.matches('input,textarea,select'))await load();}catch(error){if(error.name!=='StaleWorkspaceError'){const footer=document.querySelector('.library-footer span');if(footer)footer.textContent='Could not refresh. Your last loaded records are shown.';}}finally{if(state.loaded&&state.role==='user')ready();}},5000);void acceptFragment();}
  function readerHTML(){
    const {item,end}=reader,turns=item.content?.turns??[],segments=item.capture_segments??[],start=Math.max(0,end-40);
    const boundary=i=>item.segments>1?segments.filter(s=>s.turn_start===i||(i===start&&s.turn_start<i&&s.turn_end>i)).map(s=>`<p class="library-segment">Capture ${segments.indexOf(s)+1} · ${escape(when(s.from))}${s.portable_export?` <button class="button secondary" data-action="export-agent-capture" data-id="${escape(s.capture_id)}">Keep a private copy</button>`:''}</p>`).join(''):'';
    const navigation=turns.length>40?`<div class="library-footer"><span>Turns ${start+1}–${end} of ${turns.length}</span><div>${start?'<button class="text-button" data-action="library-earlier">← Earlier turns</button>':''}${end<turns.length?'<button class="text-button" data-action="library-later">Later turns →</button>':''}</div></div>`:'';
    return navigation+`<div class="library-conversation">${turns.length?turns.slice(start,end).map((t,i)=>`${boundary(start+i)}<article class="library-turn"><small>${escape(t.role)}</small><pre>${escape(t.content)}</pre></article>`).join(''):'<p>The original recording is saved. A readable view is not available yet.</p>'}</div>`+navigation;
  }
  async function open(id){
    const item=await api('/v1/contributor/library/'+encodeURIComponent(id));
    const segments=item.capture_segments??[];reader={item,end:item.content?.turns.length??0};
    openDialog(item.title,`${item.source} · ${item.project||'Private conversation'}`,`<div class="library-detail-status"><strong>${status(item)}</strong><span>${item.last_checkpoint_at?`Saved through ${escape(when(item.last_checkpoint_at))}`:`Added ${escape(when(item.created_at))}`}</span></div>${item.segments>1?`<p>${item.segments} captures of the same conversation. You can verify each recording below.</p>`:item.native_conversations>1?`<p>This recording contains ${item.native_conversations} native conversations, including work after a new chat or reset.</p>`:''}${display(item)?`<p class="library-attention">${escape(display(item))}. The original evidence is retained; missing display content is not a missing recording.</p>`:''}<div id="library-reader">${readerHTML()}</div>
      ${item.private_import?.can_prepare_sale?`<form id="library-prepare-sale" data-id="${escape(id)}"><h3>Want to make this trace available for sale?</h3><p>Confirm the parts you can license. This only prepares a scrubbed version; preview the price and license in Offers and sign once to enable an automatic THOT sale.</p><label class="check"><input type="checkbox" name="rights_confirmed" required> I have the right to license my contributions in this conversation.</label><label class="check"><input type="checkbox" name="model_output_licensed"> I also have the right to license the assistant responses.</label><p>Without the second choice, assistant responses are excluded. Uploaded history remains unverified.</p><button class="button secondary" type="submit">Prepare for a THOT listing</button></form>`:''}
      <form id="library-edit" data-id="${escape(id)}"><h3>Make it useful to return to</h3><div class="field"><label for="library-title">Title</label><input id="library-title" name="title" value="${escape(item.title)}" maxlength="160" required></div><div class="field"><label for="library-note">Your note</label><textarea id="library-note" name="note" maxlength="4000" placeholder="What should you remember or reuse from this conversation?">${escape(item.note)}</textarea></div><button class="button secondary" type="submit">Save title & note</button><button class="text-button" type="button" data-action="library-bookmark" data-id="${escape(id)}" data-value="${!item.bookmarked}">${item.bookmarked?'★ Remove bookmark':'☆ Bookmark for reuse'}</button></form>
      <details class="library-history"><summary>What changed in this conversation</summary><ol>${item.events.map(e=>`<li><strong>${escape(e.label)}</strong>${e.exchanges?` · ${e.exchanges} exchanges`:''}<small>${escape(when(e.at))}</small></li>`).join('')}</ol></details><details class="library-history"><summary>Source and verification</summary><p>${item.origin==='upload'?'You supplied this history. Its import receipt records the file; it does not authenticate the original provider conversation.':'Each proof covers its recorded requests and responses. Earlier history included by the coding tool is context; gaps between captures are not recorded.'}</p>${item.model_history.length?`<p>Model metadata: ${item.model_history.map(m=>`${escape(m.evidence==='user_supplied'?m.claimed_model:m.returned_model??m.model??'Unknown')} (${m.evidence==='user_supplied'?'unverified file claim':m.evidence==='request_only'?'requested; returned model unknown':'response-reported'}; exchange ${m.sequence})`).join(' → ')}</p>`:''}${item.capture_id?`${segments.map((s,i)=>`<div class="library-segment"><p>Capture ${i+1} · ${escape(when(s.from))} → ${escape(when(s.through))} · ${s.exchanges} exchanges</p><button class="button secondary" data-action="verify-agent-capture" data-id="${escape(s.capture_id)}">${segments.length>1?`Verify capture ${i+1}`:'Verify saved capture'}</button><small> Retained until ${escape(when(s.retention_expires_at))}</small></div>`).join('')}<button class="text-button" data-action="library-reprocess" data-id="${escape(id)}">Refresh readable view</button>`:''}<p>Private retention until ${escape(when(item.retention_expires_at))}.</p></details>`);
  }
  async function connections(){
    const {devices}=await api('/v1/contributor/capture-devices');
    openDialog('Connected coding tools','Manage capture access and the sale terms you authorized.',devices.length?devices.map(d=>`<article class="library-device"><strong>${escape(d.client==='claude'?'Claude Code':'Codex')} · ${escape(d.device_name)}</strong><p>${escape(d.status.toLowerCase())} · last used ${escape(when(d.last_used_at))}</p><p>${d.sale_policy_id?'This connection has a signed sale policy. It covers only eligible future completed sessions while active.':'Private recording only. To enable automatic sales, disconnect and reconnect this tool, then choose and sign its sale terms.'}</p>${d.sale_policy_id?'<p>Disconnect stops new recordings and new listings. Manage sale policies in Connections to stop offers or confirm onchain wallet revocation. Funded purchases keep their terms.</p><button class="button secondary small" data-action="openrouter-open">Manage signed sale policies</button>':''}${d.status==='CONNECTED'?`<button class="button secondary small" data-action="library-disconnect" data-id="${escape(d.device_id)}">Disconnect this tool</button>`:''}</article>`).join(''):'<p>No tools connected yet. Choose “Capture a conversation” to get started.</p>');
  }
  async function handle(action,button){
    if(action==='library-earlier'||action==='library-later'){if(reader){reader.end=Math.max(1,Math.min(reader.item.content.turns.length,reader.end+(action==='library-earlier'?-40:40)));const el=document.querySelector('#library-reader');if(el){el.innerHTML=readerHTML();el.scrollIntoView({block:'start'});}}return true;}
    if(action==='library-reprocess'){await api('/v1/contributor/library/'+encodeURIComponent(button.dataset.id)+'/refresh',{method:'POST',body:{}});toast('Refreshing the readable view from your saved recording. The original proof stays unchanged.');return true;}
    if(action==='library-open'){await open(button.dataset.id);return true;}
    if(action==='library-bookmark'){await api('/v1/contributor/library/'+encodeURIComponent(button.dataset.id),{method:'PATCH',body:{bookmarked:button.dataset.value==='true'}});await load();toast(button.dataset.value==='true'?'Bookmarked for reuse.':'Bookmark removed.');if(dialog.open)await open(button.dataset.id);return true;}
    if(action==='library-next'){previous.push(cursor);cursor=data().next_cursor;await load();return true;}
    if(action==='library-previous'){cursor=previous.pop()??'';await load();return true;}
    if(action==='library-filter-bookmarks'){bookmarked=!bookmarked;cursor='';previous=[];await load();return true;}
    if(action==='library-connections'){await connections();return true;}
    if(action==='library-disconnect'){await api('/v1/contributor/capture-devices/'+encodeURIComponent(button.dataset.id)+'/disconnect',{method:'POST',body:{}});await connections();toast('Disconnected. New captures and automatic listings stopped. Confirm wallet revocation to invalidate prepared unfunded sales on chain.');return true;}
    return false;
  }
  async function onSubmit(form){
    if(form.id==='library-prepare-sale'){
      const f=new FormData(form),rights=f.get('rights_confirmed')==='on';
      if(!rights)throw new Error('Confirm your release rights before preparing a listing.');
      if(reader?.item.trace_id!==form.dataset.id||!reader.item.private_import?.can_prepare_sale)throw new Error('Reopen this trace before preparing it for sale.');
      const result=await api('/v1/contributor/library/'+encodeURIComponent(form.dataset.id)+'/prepare-sale',{method:'POST',body:{content_commitment:reader.item.private_import.content_commitment,rights_confirmed:true,model_output_licensed:f.get('model_output_licensed')==='on'}});
      await open(form.dataset.id);await load();
      toast(result.status==='AVAILABLE'?'Ready to preview in Offers. Sign once there to authorize an automatic sale.':'This trace did not pass the release checks. It has not been listed.');return true;
    }
    if(form.id==='library-search'){const f=new FormData(form);query=String(f.get('q')??'');source=String(f.get('source')??'all');cursor='';previous=[];await load();return true;}
    if(form.id==='library-edit'){const f=new FormData(form);await api('/v1/contributor/library/'+encodeURIComponent(form.dataset.id),{method:'PATCH',body:{title:String(f.get('title')),note:String(f.get('note'))}});await load();toast('Your title and note are saved privately.');return true;}
    return false;
  }
  async function acceptFragment(){if(!state.loaded||state.role!=='user'||!/^#trace=[A-Za-z0-9-]{16,80}$/.test(location.hash))return;const id=location.hash.slice(7);history.replaceState(history.state,'',location.pathname+location.search);try{await open(id);}catch(error){toast(error.message);}}
  function reset(){clearTimeout(timer);timer=null;state.traceLibrary=null;reader=null;query='';source='all';bookmarked=false;cursor='';previous=[];}
  return {sectionHTML,queryString,ready,reset,handle,onSubmit,acceptFragment};
}

export function createTraceExplorerUI({state,api,escape,openDialog}){
  let view='inventory',filter='all',client='all',projection='',offset=0;
  const when=v=>v?new Date(v).toLocaleString():'—';
  function body(){
    const d=state.traceExplorer;if(!d)return '<p>Loading trace inventory…</p>';const s=d.summary;
    return `<p class="eyebrow">OPERATOR · TRACE EXPLORER</p><h1>What is arriving in thot market?</h1><p>Current retained inventory and capture attempts. Private conversation bodies remain in the owner’s vault.</p><section class="library-metrics"><article><small>Saved records</small><strong>${s.saved}</strong><p>+${s.added_24h} added in the last 24 hours · ${s.raw_traces??s.saved} original deposits</p><button class="text-button" data-action="explorer-inventory">Browse inventory →</button></article><article><small>Readable view needs attention</small><strong>${s.display_issues}</strong><p>${s.readable} readable · ${s.preparing} preparing</p><button class="text-button" data-action="explorer-display-issues">Inspect display issues →</button></article><article><small>Failed capture attempts</small><strong>${s.failed_attempts}</strong><p>Includes attempts with no saved conversation.</p><button class="text-button" data-action="explorer-failures">Inspect failures →</button></article></section><form id="trace-explorer-filters" class="library-toolbar"><label>View <select name="view"><option value="inventory" ${view==='inventory'?'selected':''}>Saved inventory</option><option value="attempts" ${view==='attempts'?'selected':''}>Capture attempts</option></select></label><label>Tool <select name="client"><option value="all">All tools</option><option value="claude" ${client==='claude'?'selected':''}>Claude Code</option><option value="codex" ${client==='codex'?'selected':''}>Codex</option></select></label><button type="submit" class="button secondary small">Apply / refresh</button><span>${projection?'Display issues · ':''}${filter!=='all'?escape(filter)+' · ':''}${d.total_matches} records match</span></form><div class="library-list">${d.items.length?d.items.map(item=>`<article class="library-row"><div class="library-origin">${escape(item.client)}<small>${escape(item.owner_ref)}</small></div><div class="library-description"><button class="library-title" data-action="explorer-detail" data-id="${escape(item.capture_id??item.trace_id)}">${escape(item.state.toLowerCase().replaceAll('_',' '))}</button><p>${escape(item.error_code??item.projection??'Awaiting checkpoint')}</p><p>${escape(item.trace_id??item.capture_id)}</p></div><div class="library-progress"><strong>${item.verified_exchanges} capture exchanges saved</strong><small>${item.parts} parts received</small><small>${escape(when(item.last_checkpoint_at))}</small></div></article>`).join(''):'<p class="empty">No records match these filters.</p>'}</div><div class="library-footer"><span>Updated ${escape(when(d.refreshed_at))}</span><div>${offset?'<button class="text-button" data-action="explorer-previous">← Previous</button>':''}${d.has_more?'<button class="text-button" data-action="explorer-next">Next →</button>':''}</div></div>`;
  }
  function sectionHTML(){return `<section id="trace-explorer">${body()}</section>`;}
  async function load(){const p=new URLSearchParams({view,state:filter,client,offset:String(offset),limit:'50'});if(projection)p.set('projection',projection);state.traceExplorer=await api('/v1/operator/trace-explorer?'+p);const el=document.querySelector('#trace-explorer');if(el&&(state.role==='operator_security'||state.canExplore))el.innerHTML=body();}
  async function handle(action,button){
    if(action==='explorer-detail'){const item=state.traceExplorer.items.find(i=>(i.capture_id??i.trace_id)===button.dataset.id);if(!item)return true;openDialog('Capture stage and recovery','Operational metadata; private prompts and responses are excluded.',`<dl>${Object.entries(item).map(([k,v])=>`<div class="meta-pair"><dt>${escape(k.replaceAll('_',' '))}</dt><dd>${escape(v??'—')}</dd></div>`).join('')}</dl><p>${item.error_code?'The original evidence and readable projection have separate status. Check the contributor helper’s encrypted recovery state before replaying any work.':'A saved checkpoint identifies the verified boundary; later in-flight work is outside it.'}</p>`);return true;}
    if(['explorer-inventory','explorer-display-issues','explorer-failures'].includes(action)){view=action==='explorer-failures'?'attempts':'inventory';filter=action==='explorer-failures'?'FAILED':'all';projection=action==='explorer-display-issues'?'ISSUE':'';client='all';offset=0;await load();return true;}
    if(action==='explorer-next'){offset+=50;await load();return true;}
    if(action==='explorer-previous'){offset=Math.max(0,offset-50);await load();return true;}return false;
  }
  async function onSubmit(form){const f=new FormData(form);view=String(f.get('view'));client=String(f.get('client'));filter='all';projection='';offset=0;await load();}
  return {sectionHTML,handle,onSubmit};
}
